numpy and pandas

In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("Products.csv")

In [4]:
df

    Product  Price
0    Laptop  70000
1     Mouse   1500
2  Keyboard   2000
3   Monitor  20000
4   Printer  14000

In [7]:
avg=df["Price"].mean()
avg

np.float64(21500.0)

In [17]:
# def fun():
#   for i in range(len(df)):
#     print(df[df["Price"]>avg])

In [20]:
def fun1():
  for i in range(len(df)):
    if df["Price"][i]>avg:
      print(df["Product"][i],df["Price"][i])

In [21]:
fun1()

Laptop 70000

In [38]:
df1=pd.read_csv("Book1.csv")

In [39]:
df1

        Days  Temp
0     Monday    22
1    Tuesday    44
2  Wednesday    40
3   Thursday    45
4     Friday    10
5   Saturday    25
6     Sunday    15

In [40]:
df['Temp'].min()

10

In [41]:
df['Temp'].max()

45

In [42]:
df['Temp'].mean()

np.float64(28.714285714285715)

In [43]:
def cate(Temp):
    if Temp < 20:
        return "Cold"
    elif Temp <= 30:
        return "Moderate"
    else:
        return "Hot"

In [49]:
for i in range(len(df)):
  print(df["Days"][i], cate(df["Temp"][i]))

Monday Moderate
Tuesday Hot
Wednesday Hot
Thursday Hot
Friday Cold
Saturday Moderate
Sunday Cold